version: '3'

services:
  consul:
    image: consul:latest
    networks: 
      - rmqnet
    ports:
      - "8500:8500"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    command: "agent -server -ui -client=0.0.0.0 -bootstrap-expect=1 -retry-join=consul"

  rabbitmq:
    image: rabbitmq:3-management
    env_file: .env
    networks: 
      - rmqnet
    ports:
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
      - AUTOCLUSTER_TYPE=consul
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - CONSUL_SVC=rabbitmq
      - CONSUL_SVC_ADDR_AUTO=true
      - AUTOCLUSTER_CLEANUP=true
      - CLEANUP_WARN_ONLY=false
    volumes:
      - mq_data:/var/lib/rabbitmq/mnesia
    command: /bin/bash -c "set -e; rabbitmq-plugins --offline enable rabbitmq_management; rabbitmq-plugins --offline enable rabbitmq_peer_discovery_consul; rabbitmq-plugins enable rabbitmq_consistent_hash_exchange; sleep 2s; rabbitmq-server;"

volumes:
  mq_data:

networks: 
  rmqnet:
    driver: overlay