version: '3'

services:
  consul:
    image: consul:latest
    networks: 
      - rmqnet
    ports:
      - "8500:8500"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    command: "agent -server -ui -client=0.0.0.0 -bootstrap-expect=1 -retry-join=consul"

  rabbitmq:
    build:
      context: .
      dockerfile: rabbit-mq-plugins.dockerfile
    networks: 
      - rmqnet
    ports:
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == manager]
    environment:
      - RABBITMQ_ERLANG_COOKIE=kuriertecnologia
      - RABBITMQ_DEFAULT_USER=teste
      - RABBITMQ_DEFAULT_PASS=123@teste
      - RABBITMQ_DEFAULT_VHOST=/
      - AUTOCLUSTER_TYPE=consul
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - CONSUL_SVC=rabbitmq
      - CONSUL_SVC_ADDR_AUTO=true
      - AUTOCLUSTER_CLEANUP=true
      - CLEANUP_WARN_ONLY=false
    volumes:
      - mq_data:/var/lib/rabbitmq/mnesia
    command: "rabbitmq-plugins --offline enable rabbitmq_management;rabbitmq-plugins --offline enable rabbitmq_peer_discovery_consul"

volumes:
  mq_data:

networks: 
  rmqnet:
    driver: overlay
