version: '3'

services:
  consul:
    image: consul:latest
    container_name: consul
    networks: 
      - rmqnet
    posts:
      - "8500:8500"
    enviroment:
      - CONSUL_BIND_INTERFACE=eth0
      - CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true}
    command: "agent -server -ui -client=0.0.0.0 -bootstrap-expect=1 -retry-join=consul"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    networks: 
      - rmqnet
    ports:
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
    environment:
      - RABBITMQ_ERLANG_COOKIE=kuriertecnologia
      - RABBITMQ_DEFAULT_USER=teste
      - RABBITMQ_DEFAULT_PASS=123@teste
      - RABBITMQ_DEFAULT_VHOST=/
      - AUTOCLUSTER_TYPE=consul
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - CONSUL_SVC=rabbitmq
      - CONSUL_SVC_ADDR_AUTO=true
      - AUTOCLUSTER_CLEANUP=true
      - CLEANUP_WARN_ONLY=false
    command: "rabbitmq-plugins --offline enable rabbitmq_peer_discovery_consul"
